### ISSUE TITLE
Feature Request - History

### ISSUE THREAD

**Issue by nickreynke** [cassidoo/todometer#28]
Being able to have a history in which you could review what you have done would be nice. Maybe displayed like a calendar in which you can click a specific day which identifies that you had todos that day.

**Comment by antislice** [comment]
What I have in mind is at least showing me what was completed the previous day. My use case is something simple to keep track of everything for standup, so I can easily run down the list of things I did yesterday, and then the active list is what I'm doing today.

**Comment by cassidoo** [comment]
Hahaha, yeah, the "out of sight, out of mind" is definitely what I was going for. I might add a "show finished" toggle for that so that we can all be happy. 😄 Playing with it in Sketch, will post updates here!

**Comment by Godje** [comment]
Also, if Electron allows that, you may add the option to make a reminder for the item.
What I mean by reminder, is that, for example, you can add a ASAP checkmark by the todo item. And then it will send a Windows notification (like the one in Windows 10 on the right bottom. Something like a Chrome notification, I think you get what I am talking about) every other 2 (would be good to have a way to set it by yourself) minutes or so, so that you don't forget you have stuff to do.

**Comment by nickreynke** [comment]
Hey @cassidoo :) Any updates on this? Also happy new year!

**Comment by cassidoo** [comment]
Fixed this in the new version (added a "completed" section), coming soon™
