### ISSUE TITLE
App built too big in macOS

### ISSUE THREAD

**Issue by gitforziio** [cassidoo/todometer#50]
The APP is 127MB (in macOS) but with such a simple function, why does this APP so huge?

**Comment by schmanat** [comment]
I think it's so big, because the app ist built with Electron. Electron is, simple said, a bundle of Chrome and NodeJS. Both of them are huge software packages.

**Comment by cassidoo** [comment]
It's definitely because it's built in Electron. I'll see what I can do to minify things better. Thanks for bringing this up, @gitforziio!

**Comment by gitforziio** [comment]
After all, I do like this App, thank you!

**Comment by jtoy** [comment]
what is it at now?

**Comment by cassidoo** [comment]
Working on the new version now and hoping it'll be smaller. Unfortunately Electron is indeed the reason it's so big, and though I've reduced it, it can't go much below this amount. In the future I'll look into other desktop frameworks for a minor version, potentially, otherwise it's going to be at or around this size.
